"""P11 step 8: generate a postmortem from real session results (what the P9
analyst does). Usage: write_postmortem.py <repo_root>"""

import json
import sys
from pathlib import Path

root = Path(sys.argv[1])
sid = "sma-cross-demo"
res = json.loads((root / f"data/results/{sid}/paper_result.json").read_text())
bt = json.loads((root / f"data/results/{sid}/backtest_result.json").read_text())


def delta(a: float, b: float) -> float:
    return round(a - b, 3)


page = f"""---
type: postmortem
created: 2026-07-19
---

# {sid} — paper — P11 integration run

Generated by the integration test from real session results.

## Expected vs realised

| Metric | Expected (backtest) | Realised (paper) | Delta |
|---|---|---|---|
| Sharpe | {bt['metrics']['sharpe']} | {res['metrics']['sharpe']} | {delta(res['metrics']['sharpe'], bt['metrics']['sharpe'])} |
| Max drawdown % | {bt['metrics']['max_drawdown_pct']} | {res['metrics']['max_drawdown_pct']} | {delta(res['metrics']['max_drawdown_pct'], bt['metrics']['max_drawdown_pct'])} |
| Trades | — | {res['metrics']['num_trades']} | — |

## Guardrail / execution events

None (dry-run sim).

## Verdict & follow-ups

Toy strategy; the value here is that the loop ran unattended through every
stage. Follow-up filed for the orchestrator: replace the SMA wire with a
real [[market-structure-shift]] signal.

## Links

- Strategy: [[sma-cross-demo]]
- Results: `data/results/{sid}/backtest_result.json`,
  `data/results/{sid}/paper_result.json`
"""
out = root / "brain/wiki/postmortems/sma-cross-demo-p11.md"
out.write_text(page)
print(f"    wrote {out}")
