//! Golden test for the ADR-0002 Python->Rust handoff of the ms_shift family.
//!
//! The fixture is generated by the Python strategy
//! (sandbox/backtest/strategies/ms_shift_spy.py). We replay it through the
//! Rust interpreter exactly as the engine does — feeding the growing OHLC
//! window bar by bar and taking the weight at each step — and require the
//! Rust series to equal the Python series bit-for-bit. If either side's logic
//! drifts, this fails. Regenerate the fixture from Python when the strategy
//! intentionally changes.

use std::collections::VecDeque;
use std::path::PathBuf;

use engine_core::engine::{Bar, Ruleset};
use serde_json::Value;

#[test]
fn ms_shift_matches_python_golden() {
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ms_shift_golden.json");
    let fixture: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

    // Build a full ms_shift Ruleset around the fixture's params.
    let ruleset: Ruleset = serde_json::from_value(serde_json::json!({
        "schema_version": "1.0.0",
        "strategy_id": "ms-shift-golden",
        "family": "ms_shift",
        "max_position_pct": 5.0,
        "params": fixture["params"],
        "data_snapshot": {
            "parquet_path": "data/x.parquet",
            "content_hash": "sha256:9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
            "source_feed": "synthetic_test",
            "period": {"start": "2021-01-04", "end": "2021-12-31"}
        }
    }))
    .unwrap();

    let bars_json = fixture["bars"].as_array().unwrap();
    let expected = fixture["expected_weights"].as_array().unwrap();
    assert_eq!(bars_json.len(), expected.len());

    // Replay: window grows bar by bar (history_window = 400 > fixture length,
    // so no eviction — the window always covers full history, matching the
    // Python full-history walk).
    let mut window: VecDeque<Bar> = VecDeque::new();
    for (t, b) in bars_json.iter().enumerate() {
        window.push_back(Bar {
            symbol: "SPY".into(),
            date: format!("2021-{:03}", t),
            open: b["close"].as_f64().unwrap(),
            high: b["high"].as_f64().unwrap(),
            low: b["low"].as_f64().unwrap(),
            close: b["close"].as_f64().unwrap(),
            volume: 1.0,
        });
        let got = ruleset.target_weight(&window);
        let want = expected[t].as_f64().unwrap();
        assert_eq!(got, want, "weight diverged at bar {t}");
    }
}
